# Configured for Apple Silicon (M1/M2) Macs with platform: linux/amd64

services:
  spark:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spark-hadoop:latest
    platform: linux/amd64
    hostname: master
    container_name: spark-hadoop-master
    networks:
      - spark-hadoop-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./share:/opt/share
    ports:
      - '8080:8080'
      - '4040:4040'
      - '7077:7077'
      - '8088:8088'
      - '8042:8042'
      - '9870:9870'
      - '19888:19888'
    command: >
      bash -c "/opt/start-hadoop.sh && 
               /opt/bitnami/scripts/spark/run.sh"

  spark-worker-1:
    image: spark-hadoop:latest
    platform: linux/amd64
    hostname: worker1
    container_name: spark-hadoop-worker-1
    networks:
      - spark-hadoop-network
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./share:/opt/share
    ports:
      - '8081:8081'

  spark-worker-2:
    image: spark-hadoop:latest
    platform: linux/amd64
    hostname: worker2
    container_name: spark-hadoop-worker-2
    networks:
      - spark-hadoop-network
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./share:/opt/share
    ports:
      - '8082:8081'

networks:
  spark-hadoop-network:
    driver: bridge
